version: '3.8'

services:
  web_md:
    build:
      context: ./
      dockerfile: WebServer.Dockerfile
    environment:
      ConnectionDatabaseSettings:ConnectionString: mongodb://mongo:27017/db_md
      ConnectionDatabaseSettings:DatabaseName: db_md
      ConnectionStrings:MessageBroker: Host=rabbitmq;Port=5672;Username=root;Password=root
    ports:
      - 8000:80
      - 8001:443
    depends_on:
      - rabbitmq
      - mongo

  web_us:
    build:
      context: ./
      dockerfile: WebServer.Dockerfile
    environment:
      ConnectionDatabaseSettings:ConnectionString: mongodb://mongo:27017/db_us
      ConnectionDatabaseSettings:DatabaseName: db_us
      ConnectionStrings:MessageBroker: Host=rabbitmq;Port=5672;Username=root;Password=root
    ports:
      - 9000:80
      - 9001:443
    depends_on:
      - rabbitmq
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root     
    ports:
      - 5672:5672
      - 15672:15672
